# Site/SEO settings
email: siknucha@gmail.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: LearningB
title: Anityam looking through data
description: >
  Anityam is journey for exploration of data.
url: 
twitter_username: 
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: 
  - name: instagram
    url: 
  - name: linkedin
    url: 
  - name: github
    url: 
  - name: codepen
    url: 

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Bjn
    bio: 
    url: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
